### register route
POST  http://localhost:5050/user/register
Content-Type: application/json

{
    "firstName": "Ravi",
    "lastName": "Pathekar",
    "contactNumber": "9993532964",
    "email": "ravipathekar88@gmail.com",
    "isActive": "true",
    "password": "0123456"
}

### Login route
POST  http://localhost:5050/user/login
Content-Type: application/json

{
    "email": "ravipathekar88@gmail.com",
    "password": "0123456"
}

### refresh-token route
POST  http://localhost:5050/user/refresh-token
Content-Type: application/json

{
    "refreshToken": "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpYXQiOjE2MDYyMTk5NzgsImV4cCI6MTYzNzc3NzU3OCwiYXVkIjoiNWZiY2Y4MGY5M2YzYzA1YWRkZjVmZDA3IiwiaXNzIjoicGlja3VycGFnZS5jb20ifQ.H92i42tWp50ISXXa8qaEscvxvP8p0LAxy2VFhP5lC_Y"
}

### Logout route
DELETE  http://localhost:5050/user/logout
Content-Type: application/json

{
    "refreshToken": "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpYXQiOjE2MDYyMTk5NzgsImV4cCI6MTYzNzc3NzU3OCwiYXVkIjoiNWZiY2Y4MGY5M2YzYzA1YWRkZjVmZDA3IiwiaXNzIjoicGlja3VycGFnZS5jb20ifQ.H92i42tWp50ISXXa8qaEscvxvP8p0LAxy2VFhP5lC_Y"
}

### Reset-Password Route
POST http://localhost:5050/user/resetPassword
Content-Type: application/json

{
    "email": "ravipathekar88@gmail.com"
}